### ISSUE TITLE
Moirai Model got some update 

### ISSUE THREAD

**Issue by kavururajesh** [readytensor/rt_forecasting_moirai#1]
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/Salesforce/moirai-1.0-R-base/resolve/main/model.ckpt facing this issue 

This is working can you please update the code in your repo:

from uni2ts.model.moirai import MoiraiForecast, MoiraiModule

# Prepare model
model = MoiraiForecast(
    module=MoiraiModule.from_pretrained(
        f"Salesforce/moirai-1.0-R-{SIZE}",
    ),
    prediction_length=metadata.prediction_length,
    context_length=CTX,
    patch_size=PSZ,
    num_samples=100,
    target_dim=metadata.target_dim,
    feat_dynamic_real_dim=metadata.feat_dynamic_real_dim,
    past_feat_dynamic_real_dim=metadata.past_feat_dynamic_real_dim,
)

**Comment by Mo-Abdelhameed** [comment]
The code was updated to download the models without this error
